name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Set up JDK (for Maven builds)
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'
    
    # Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    # Run Style Analysis (e.g., using Checkstyle)
    - name: Run Checkstyle
      run: mvn checkstyle:check

    # Build the code (both release and debug)
    - name: Build project
      run: mvn clean install

    # Run unit tests
    - name: Run tests
      run: mvn test

    # Generate and publish Javadoc
    - name: Generate Javadoc
      run: mvn javadoc:javadoc

    # Upload Javadoc to GitHub Pages (optional for publishing)
    - name: Deploy Javadoc to GitHub Pages
      run: |
        mvn javadoc:javadoc
        mkdir -p docs
        mv target/site/apidocs/* docs/
    
    - name: Commit and push Javadoc to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add docs/*
        git commit -m "Update Javadoc"
        git push origin HEAD:gh-pages
