name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed to push to gh-pages

      - name: Set up Zulu JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'zulu'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p docs
          for dir in database legal menu resource-files script-files; do
            if [ -d "$dir" ]; then
              rm -rf "docs/$dir"
              mv "$dir" docs/
            fi
          done

      - name: Commit and push to gh-pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git switch --orphan gh-pages || git checkout gh-pages
          git rm -rf . > /dev/null 2>&1 || true
          cp -r docs/* .
          git add .
          git commit -m "Deploy docs to GitHub Pages" || echo "Nothing to commit"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
