name: CI/CD

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Zulu JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'zulu'

      # Run Style Analysis (e.g., using Checkstyle)
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # Build the code (both release and debug)
      - name: Build project
        run: mvn clean install

      # Run unit tests
      - name: Run tests
        run: mvn test

      # Generate and publish Javadoc
      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      # Upload Javadoc to GitHub Pages (optional for publishing)
      - name: Deploy Javadoc to GitHub Pages
        run: |
          mkdir -p docs
          mv target/site/apidocs/* docs/

      - name: Commit and push Javadoc to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add docs/*
          git commit -m "Update Javadoc"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
